# Generated by Django 3.2.2 on 2021-05-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210508_0114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='customers',
            name='password',
            field=models.CharField(max_length=500),
        ),
    ]
