# Generated by Django 3.2.2 on 2021-05-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
