# Generated by Django 3.2.2 on 2021-05-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_category_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Active',
            field=models.BooleanField(default=False),
        ),
    ]
