# Generated by Django 3.2.2 on 2021-05-10 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_customer_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
